param(
    [string]$WorkspaceRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,
    [switch]$Apply,
    [switch]$IncludePcTemp,
    [int]$KeepDbBackups = 1,
    [switch]$AllowDeleteVenv,
    [switch]$AggressiveWorkspace,
    [switch]$CompactSqlite
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Get-DirSizeBytes {
    param([Parameter(Mandatory=$true)][string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) { return 0 }
    $measure = Get-ChildItem -LiteralPath $Path -File -Recurse -ErrorAction SilentlyContinue |
        Measure-Object -Property Length -Sum
    if (-not $measure -or $null -eq $measure.Sum) { return 0 }
    return [int64]$measure.Sum
}

function Format-Bytes {
    param([double]$Bytes)
    if ($Bytes -ge 1TB) { return ('{0:N2} TB' -f ($Bytes / 1TB)) }
    if ($Bytes -ge 1GB) { return ('{0:N2} GB' -f ($Bytes / 1GB)) }
    if ($Bytes -ge 1MB) { return ('{0:N2} MB' -f ($Bytes / 1MB)) }
    if ($Bytes -ge 1KB) { return ('{0:N2} KB' -f ($Bytes / 1KB)) }
    return ('{0} B' -f [int64]$Bytes)
}

function Add-DeletionCandidate {
    param(
        [Parameter(Mandatory=$true)][string]$Path,
        [Parameter(Mandatory=$true)][string]$Reason,
        [System.Collections.IList]$List
    )

    if (-not (Test-Path -LiteralPath $Path)) { return }

    if (Test-Path -LiteralPath $Path -PathType Leaf) {
        $size = (Get-Item -LiteralPath $Path).Length
        $List.Add([pscustomobject]@{ Path = $Path; Type = 'File'; Size = $size; Reason = $Reason })
    } elseif (Test-Path -LiteralPath $Path -PathType Container) {
        $size = Get-DirSizeBytes -Path $Path
        $List.Add([pscustomobject]@{ Path = $Path; Type = 'Dir'; Size = $size; Reason = $Reason })
    }
}

function Remove-Candidate {
    param([Parameter(Mandatory=$true)]$Candidate)
    if (-not (Test-Path -LiteralPath $Candidate.Path)) { return }

    if ($Candidate.Type -eq 'File') {
        Remove-Item -LiteralPath $Candidate.Path -Force -ErrorAction SilentlyContinue
    } else {
        Remove-Item -LiteralPath $Candidate.Path -Recurse -Force -ErrorAction SilentlyContinue
    }
}

function Invoke-SqliteCompact {
    param([Parameter(Mandatory=$true)][string]$WorkspaceRoot)

    $py = Join-Path $WorkspaceRoot '.venv\Scripts\python.exe'
    $db = Join-Path $WorkspaceRoot 'data\cnpj_database.db'

    if (-not (Test-Path -LiteralPath $py)) {
        Write-Warning 'Python da venv nao encontrado; pulando compactacao SQLite.'
        return
    }
    if (-not (Test-Path -LiteralPath $db)) {
        Write-Warning 'Banco principal nao encontrado; pulando compactacao SQLite.'
        return
    }

    $code = @"
import sqlite3
db = r'''$db'''
con = sqlite3.connect(db, timeout=60)
cur = con.cursor()
cur.execute('PRAGMA wal_checkpoint(TRUNCATE)')
print('wal_checkpoint', cur.fetchall())
cur.execute('VACUUM')
con.commit()
con.close()
print('sqlite_compact_done')
"@

    Write-Host 'Running SQLite compact (checkpoint + VACUUM)...' -ForegroundColor Yellow
    & $py -c $code
}

Write-Host '=== Deep Clean Safe ===' -ForegroundColor Cyan
Write-Host "Workspace: $WorkspaceRoot"
$mode = 'DRY-RUN'
if ($Apply) { $mode = 'APPLY' }
Write-Host "Mode: $mode"

$wsBefore = Get-DirSizeBytes -Path $WorkspaceRoot
Write-Host ("Workspace before: {0}" -f (Format-Bytes $wsBefore))

$candidates = New-Object 'System.Collections.Generic.List[object]'

# 1) Workspace temporary files (safe)
Get-ChildItem -LiteralPath $WorkspaceRoot -File -Recurse -ErrorAction SilentlyContinue |
    Where-Object {
        $_.FullName -notmatch [regex]::Escape('\.venv\') -and (
            $_.Name -like 'temp_*' -or
            $_.Name -like '_tmp_*' -or
            $_.Extension -in @('.tmp', '.log', '.err')
        )
    } |
    ForEach-Object { Add-DeletionCandidate -Path $_.FullName -Reason 'Workspace temporary/log file' -List $candidates }

# 2) Python cache folders
Get-ChildItem -LiteralPath $WorkspaceRoot -Directory -Recurse -ErrorAction SilentlyContinue |
    Where-Object {
        $_.Name -in @('__pycache__', '.pytest_cache', '.mypy_cache', '.ruff_cache') -and
        ($AllowDeleteVenv -or $_.FullName -notmatch [regex]::Escape('\.venv\'))
    } |
    ForEach-Object { Add-DeletionCandidate -Path $_.FullName -Reason 'Python cache folder' -List $candidates }

# 3) Export leftovers in workspace root
Get-ChildItem -LiteralPath $WorkspaceRoot -File -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -like 'cnpj_exportacao_*.csv' } |
    ForEach-Object { Add-DeletionCandidate -Path $_.FullName -Reason 'Old root export CSV' -List $candidates }

# 4) Old temp exports generated by app in user temp
$appTempExportDir = Join-Path $env:TEMP 'cnpj_exports'
if (Test-Path -LiteralPath $appTempExportDir) {
    Get-ChildItem -LiteralPath $appTempExportDir -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -like 'cnpj_exportacao_*.csv' } |
        ForEach-Object { Add-DeletionCandidate -Path $_.FullName -Reason 'App temp export CSV' -List $candidates }
}

# 5) DB backups retention (largest practical gain)
$dbPattern = Join-Path (Join-Path $WorkspaceRoot 'data') 'cnpj_database.db.bak_*.db'
$dbBackups = @(Get-ChildItem -Path $dbPattern -File -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending)
if ($dbBackups.Count -gt $KeepDbBackups) {
    $toDelete = $dbBackups | Select-Object -Skip $KeepDbBackups
    foreach ($f in $toDelete) {
        Add-DeletionCandidate -Path $f.FullName -Reason ("DB backup beyond keep={0}" -f $KeepDbBackups) -List $candidates
    }
}

# 6) Optional aggressive workspace cleanup
if ($AggressiveWorkspace) {
    $aggressiveGlobs = @(
        (Join-Path $WorkspaceRoot 'archive\*.bak_*'),
        (Join-Path $WorkspaceRoot 'archive\*.json.bak_*'),
        (Join-Path $WorkspaceRoot 'data\exports\*.csv')
    )
    foreach ($g in $aggressiveGlobs) {
        Get-ChildItem -Path $g -File -ErrorAction SilentlyContinue |
            ForEach-Object { Add-DeletionCandidate -Path $_.FullName -Reason 'Aggressive workspace cleanup' -List $candidates }
    }
}

# 7) Optional PC temp cleanup (user scope only)
if ($IncludePcTemp) {
    $pcTempTargets = @(
        $env:TEMP,
        (Join-Path $env:LOCALAPPDATA 'Temp')
    ) | Select-Object -Unique

    foreach ($t in $pcTempTargets) {
        if (-not (Test-Path -LiteralPath $t)) { continue }

        Get-ChildItem -LiteralPath $t -Force -ErrorAction SilentlyContinue |
            Where-Object {
                $_.Name -notin @('pip', 'pip-cache', 'npm-cache')
            } |
            ForEach-Object {
                Add-DeletionCandidate -Path $_.FullName -Reason 'User temp cleanup' -List $candidates
            }
    }
}

# Deduplicate by path
$dedup = $candidates |
    Group-Object -Property Path |
    ForEach-Object { $_.Group | Sort-Object Size -Descending | Select-Object -First 1 }

$totalReclaim = ($dedup | Measure-Object -Property Size -Sum).Sum
if (-not $totalReclaim) { $totalReclaim = 0 }

Write-Host ''
Write-Host 'Top cleanup candidates:' -ForegroundColor Yellow
$dedup | Sort-Object Size -Descending | Select-Object -First 30 |
    ForEach-Object {
        Write-Host ("- {0} | {1} | {2}" -f (Format-Bytes $_.Size), $_.Reason, $_.Path)
    }

Write-Host ''
Write-Host ("Estimated reclaimable: {0}" -f (Format-Bytes $totalReclaim)) -ForegroundColor Green

if (-not $Apply) {
    Write-Host ''
    Write-Host 'Dry-run only. No files were deleted.' -ForegroundColor Cyan
    Write-Host 'To apply:' -ForegroundColor Cyan
    Write-Host '  .\scripts\deep_clean_safe.ps1 -Apply -KeepDbBackups 1'
    Write-Host 'Optional PC temp cleanup:'
    Write-Host '  .\scripts\deep_clean_safe.ps1 -Apply -KeepDbBackups 1 -IncludePcTemp'
    Write-Host 'Optional aggressive workspace cleanup:'
    Write-Host '  .\scripts\deep_clean_safe.ps1 -Apply -KeepDbBackups 1 -AggressiveWorkspace'
    Write-Host 'Optional SQLite compact (backend deve estar parado):'
    Write-Host '  .\scripts\deep_clean_safe.ps1 -Apply -CompactSqlite'
    exit 0
}

Write-Host ''
Write-Host 'Applying cleanup...' -ForegroundColor Yellow

$deletedCount = 0
foreach ($c in $dedup) {
    try {
        Remove-Candidate -Candidate $c
        $deletedCount++
    } catch {
        Write-Warning ("Failed to delete: {0} | {1}" -f $c.Path, $_.Exception.Message)
    }
}

if ($CompactSqlite) {
    try {
        Invoke-SqliteCompact -WorkspaceRoot $WorkspaceRoot
    } catch {
        Write-Warning ("SQLite compact falhou: {0}" -f $_.Exception.Message)
    }
}

$wsAfter = Get-DirSizeBytes -Path $WorkspaceRoot
$actualFreed = $wsBefore - $wsAfter
if ($actualFreed -lt 0) { $actualFreed = 0 }

Write-Host ''
Write-Host ("Deleted entries: {0}" -f $deletedCount) -ForegroundColor Green
Write-Host ("Workspace after: {0}" -f (Format-Bytes $wsAfter)) -ForegroundColor Green
Write-Host ("Actual workspace freed: {0}" -f (Format-Bytes $actualFreed)) -ForegroundColor Green
Write-Host 'Done.' -ForegroundColor Cyan
